apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: calculator
  clusterIP: 10.99.132.220
  externalTrafficPolicy: Cluster
  ports:
  - name: myport
    protocol: TCP
    port: 8037
    targetPort: 3000
  type: LoadBalancer
