apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend 
spec:
  containers:
  - image: duozhang/my-calculator:latest
    name: my-node-app 
    ports: 
    - containerPort: 3000
  dnsPolicy: ClusterFirst
  restartPolicy: Always